### ISSUE TITLE
Indexed Arrays after parsing

### ISSUE THREAD

**Issue by Ndhb478** [lichunqiang/yii2-xmlparser#2]
Hi,
I want to use your parser but I have a problem.

I send via POST the following:

```
 <orders>
      <order id="58382388">
      <item id="6" count="1" />
     </order>
         <order id="58382386">
      <item id="8" count="1" />
  </order>
</orders>
```

Your parser then returns an indexed array which I can access like this: $arrays['order'][0]['item'].
But if I send only one order I get an non indexed array: $arrays['order']['item']

```
 <orders>
      <order id="58382388">
      <item id="6" count="1" />
     </order>
</orders>
```

From my point of view this makes it more complex, unnecessarily. Classic SimpleXML Parser delivers always indexed arrays. Much easier to work with...

**Comment by lichunqiang** [comment]
Used the `simplexml_load_string` to load the xml string, and it will return the `SimpleXMLElement` object.

you can config like this to return the original `SimpleXMLElement`:

```
'parsers' => [
    'application/xml' => ['class' => XmlParser::className(), 'asArray' => false],
],
```

in my opinion, you should judge the parsed result by yourself..
