### ISSUE TITLE
How do I use it? documentation?

### ISSUE THREAD

**Issue by dantux** [lichunqiang/yii2-xmlparser#4]

**Comment by dantux** [comment]
Sorry, to write this as an issue, but I just added it to the components (which was not obvious at first). How do I use it if I want to import an external XML file?

Thanks!

**Comment by lichunqiang** [comment]
> want to import an external XML file

I wrote this to help us handle xml style request. 

As we know, Yii2 has one builtin request parser for json like request.

If i don't misunderstand your thought, you want to parse a xml file directly?

**Comment by dantux** [comment]
:) Yes, maybe I misunderstood the purpose of your code. What would you use to parse and import/export XML files? I have a third party app that could send me some information. I was thinking using XML is the best way to handle this problem. I haven't used the JSON request in Yii apart from outputting the data when dealing with ajax.

**Comment by lichunqiang** [comment]
maybe `yii\web\XmlResponseFormatter` can give you inspiration

**Comment by dantux** [comment]
Thanks lichunqiang. I'll have a look at that.
